### ISSUE TITLE
Getting None returned from geojson file

### ISSUE THREAD

**Issue by aclifton314** [tammoippen/geopip#2]
OS: Pop!_OS 22.04 LTS
Python: 3.12.0
geopip: 1.1

I downloaded the `ne_110m_populated_places.json` file from https://github.com/martynafford/natural-earth-geojson and set the `REVERSE_GEOCODE_DATA` environment variable to the location of this file. I have the following test code:
```python
import geopip

#Denver
tmp = geopip.search(lng=-104.984015952, lat=39.7391880484)
print(tmp)
```
and I get `None` returned. It looks like from the repo of the geojson file that Denver is included in the file: https://github.com/martynafford/natural-earth-geojson/blob/master/110m/cultural/ne_110m_populated_places.json. I was wondering if I were doing something incorrect to get the `None` value returned? Thank you in advanced for your help!

**Comment by tammoippen** [comment]
Hi @aclifton314 ,

Thank you for your interest in the project! When looking at the provided geojson, than you only have points (`"type": "Point",`), e.g.:

```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "SCALERANK": 8,
                "NATSCALE": 10,
                "LABELRANK": 3,
                ...
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    12.453386544971766,
                    41.903282179960115
                ]
            }
        },
        ...
    ]
}
```
geopip can only work with Polygon and MultiPolygon features - points will be ignored.

You can go to https://geojson.io, open the geojson file and have a look at the structure:

<img width="686" alt="Screenshot 2023-10-17 at 14 05 54" src="https://github.com/tammoippen/geopip/assets/4425925/1c0681ba-2a86-4c50-a5a3-2125c6512981">
